image: node:11.15.0

stages:
  - install
  - quality
  # - build (if deploying)

include:
  - template: Code-Quality.gitlab-ci.yml

install:
   stage: install
   script:
      - npm install
   artifacts:
      name: "artifacts"
      untracked: true
      expire_in: 30 mins
      paths:
        - .npm/
        - node_modules/

linting:
  stage: quality
  script:
    - npm run lintfix
  dependencies:
    - install

tests:
  stage: quality
  script:
    - cd functions
    - npm install
    - cd ..
    - npm run test
  dependencies:
    - install
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/

# build:
#    stage: build
#    script:
#       - npm run build
#    artifacts:
#       paths:
#          - build
#       expire_in: 30 mins
#    dependencies:
#       - install

code_quality:
  stage: quality
  image: docker:stable
  allow_failure: true
  services:
    - docker:stable-dind
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  script:
    - docker info
    - docker run 
      --env CODECLIMATE_DEBUG=1 
      --env CODECLIMATE_CODE="$PWD" 
      --volume "$PWD":/code 
      --volume /var/run/docker.sock:/var/run/docker.sock 
      --volume /tmp/cc:/tmp/cc 
      codeclimate/codeclimate:0.85.2 analyze -f html > gl-code-quality-report.json
  artifacts:
    paths: [gl-code-quality-report.json]
    expire_in: 10 weeks
  dependencies:
    - install
  except:
    variables:
      - $CODE_QUALITY_DISABLED
